apiVersion: v1
kind: Pod
metadata:
    name: fastapi
    labels:
        app.kubernetes.io/name: fastapi
spec:
    containers:
        - name: fastapi
          image: fastapi-simple:latest
          imagePullPolicy: Never 
          ports:
                - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
    name: backend
spec:
    selector:
        app.kubernetes.io/name: fastapi
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: fastapi-ingress
spec:
    ingressClassName: nginx
    rules:
        - http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: backend
                        port:
                            number: 80

---